### ISSUE TITLE
Want to show more history work log

### ISSUE THREAD

**Issue by exosite-RobertChen** [dang113108/JIRA-Tracker#16]

**Comment by dang113108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[0.2] 希望能夠看到更久以前的Log](https://trello.com/c/GoEVPCK6/1-02-%E5%B8%8C%E6%9C%9B%E8%83%BD%E5%A4%A0%E7%9C%8B%E5%88%B0%E6%9B%B4%E4%B9%85%E4%BB%A5%E5%89%8D%E7%9A%84log)
