### ISSUE TITLE
Show the recent view ticket

### ISSUE THREAD

**Issue by exosite-RobertChen** [dang113108/JIRA-Tracker#18]

**Comment by dang113108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[0.2] 顯示最近開啟過的Ticket](https://trello.com/c/BulqaDNH/2-02-%E9%A1%AF%E7%A4%BA%E6%9C%80%E8%BF%91%E9%96%8B%E5%95%9F%E9%81%8E%E7%9A%84ticket)
