### ISSUE TITLE
Choose ticket will show option list

### ISSUE THREAD

**Issue by exosite-RobertChen** [dang113108/JIRA-Tracker#32]

**Comment by exosite-RobertChen** [comment]
#33

**Comment by dang113108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[0.2.0] 修正選完 Ticket 後 Dropdown會再次開啟](https://trello.com/c/NDsRMZUo/13-020-%E4%BF%AE%E6%AD%A3%E9%81%B8%E5%AE%8C-ticket-%E5%BE%8C-dropdown%E6%9C%83%E5%86%8D%E6%AC%A1%E9%96%8B%E5%95%9F)
