### ISSUE TITLE
Save 1h time will become 1m

### ISSUE THREAD

**Issue by exosite-RobertChen** [dang113108/JIRA-Tracker#35]

**Comment by dang113108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[HotFix] Submit一小時會變一分鐘](https://trello.com/c/RaV0SVgX/5-hotfix-submit%E4%B8%80%E5%B0%8F%E6%99%82%E6%9C%83%E8%AE%8A%E4%B8%80%E5%88%86%E9%90%98)
