### ISSUE TITLE
The real work time is not match the Tracker

### ISSUE THREAD

**Issue by exosite-RobertChen** [dang113108/JIRA-Tracker#36]

**Comment by dang113108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[0.2] Tracker上與JIRA上的時間不一致](https://trello.com/c/int51Vbc/6-02-tracker%E4%B8%8A%E8%88%87jira%E4%B8%8A%E7%9A%84%E6%99%82%E9%96%93%E4%B8%8D%E4%B8%80%E8%87%B4)
