### ISSUE TITLE
Add release note to the app

### ISSUE THREAD

**Issue by exosite-RobertChen** [dang113108/JIRA-Tracker#52]

**Comment by dang113108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[0.3] 顯示被噁賽的Code reivew](https://trello.com/c/rF7lI0gb/4-03-%E9%A1%AF%E7%A4%BA%E8%A2%AB%E5%99%81%E8%B3%BD%E7%9A%84code-reivew)

**Comment by dang113108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[0.2] 新增並顯示Release Note在Popup上](https://trello.com/c/PgICCoBb/7-02-%E6%96%B0%E5%A2%9E%E4%B8%A6%E9%A1%AF%E7%A4%BArelease-note%E5%9C%A8popup%E4%B8%8A)
