### ISSUE TITLE
Improve the login time judge

### ISSUE THREAD

**Issue by exosite-RobertChen** [dang113108/JIRA-Tracker#56]

**Comment by dang113108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[0.2.0] 改善打 Login API 的邏輯](https://trello.com/c/GCvqLZb8/8-020-%E6%94%B9%E5%96%84%E6%89%93-login-api-%E7%9A%84%E9%82%8F%E8%BC%AF)
