### ISSUE TITLE
Some work log can not calc money like English class

### ISSUE THREAD

**Issue by exosite-RobertChen** [dang113108/JIRA-Tracker#61]
INT-7

**Comment by dang113108** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[0.2.0] 扣除上英文課的時間](https://trello.com/c/RmBFJ7hA/11-020-%E6%89%A3%E9%99%A4%E4%B8%8A%E8%8B%B1%E6%96%87%E8%AA%B2%E7%9A%84%E6%99%82%E9%96%93)
